### ISSUE TITLE
get不到cookies

### ISSUE THREAD

**Issue by gaopeng990618** [yym68686/tgbot#1]
今天学校似乎把登陆机制改了 现在https://m.nuaa.edu.cn/uc/wap/login好像访问不了了

**Comment by yym68686** [comment]
确实，难顶。目前打卡功能应该是用不了了。

**Comment by IQIUM** [comment]
刚在尝试手机抓包，登录url变了一个，但学校的手机app那个好像有反抓包机制，没抓成功，不知道大佬有没有什么好方法

**Comment by yym68686** [comment]
> 刚在尝试手机抓包，登录url变了一个，但学校的手机app那个好像有反抓包机制，没抓成功，不知道大佬有没有什么好方法

试试这个：https://github.com/desperadoccy/inuaa

**Comment by IQIUM** [comment]
刚尝试了一下，跟之前的代码差不多，主要是get_uid_id获取id的url不能用了，到这一步就停止了
